### ISSUE TITLE
You do not have permission to access tuned model tunedModels/mymodel

### ISSUE THREAD

**Issue by Iven2132** [google-gemini/generative-ai-js#240] opened 2024-08-28 09:44 UTC
### Description of the bug:

Hi, I am getting this error:  `GoogleGenerativeAIFetchError: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/tunedModels/mymodel:generateContent: [403 Forbidden] You do not have permission to access tuned model tunedModels/mymodel`

### Actual vs expected behavior:

It should give me the model output from my tuned model 

### Any other information you'd like to share?

I have OAuth setup and can use the Python SDK to run the model, but what's wrong with the Node.js SDK?

**Comment by Iven2132** [comment] 2024-08-29 11:24
is @hsubox76 on vacation?

**Comment by hsubox76** [comment] 2024-08-29 19:20
Duplicate of https://github.com/google-gemini/generative-ai-js/issues/100

**Closed by hsubox76** 2024-08-29 19:20 UTC
Labels: status:duplicate, type:help, component:other

**Comment by Iven2132** [comment] 2024-08-30 14:23
@hsubox76 So when will this get fixed? What's the solution? It's been 4 months.

**Comment by Iven2132** [comment] 2024-09-04 06:42
@hsubox76 ??

**Comment by Iven2132** [comment] 2024-09-04 06:43
@lahirumaramba @hsubox76  ??
